FROM n8nio/n8n

ENV N8N_BASIC_AUTH_ACTIVE=true
ENV N8N_BASIC_AUTH_USER=admin
ENV N8N_BASIC_AUTH_PASSWORD=ms800869
ENV N8N_HOST=0.0.0.0
ENV N8N_PORT=5678
ENV ENV WEBHOOK_TUNNEL_URL=https://n8n-render-host-nju6.onrender.com
ENV N8N_RUNNERS_ENABLED=true
ENV N8N_ENFORCE_SETTINGS_FILE_PERMISSIONS=true

EXPOSE 5678
