services:
  - type: web
    name: n8n-agent
    env: docker
    plan: free
    envVars:
      - key: N8N_BASIC_AUTH_USER
        value: admin
      - key: N8N_BASIC_AUTH_PASSWORD
        value: ms800869
